stalker:
       world: world
#мир в котором необходим выброс
       rand: true
       time: 600
       poison: 100
# rand: возможные значения true и false ! если true то время между выбросами рандомное
# если false то время берется из time ! значения в time целые числа! 1 сек = 20 тиков! время указывать в тиках.
# poison - время отравления зомби в тиках.


# Plugin by Failer 
# failerept8@gmail.com
# спасибки сюда:
# R261034216073
# Z221643925630
# Обо всех ошибках писать сюда : failerept8@gmail.com